const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
const EMAIL_ALREADY_SIGNED_UP = 'EMAIL_ALREADY_SIGNED_UP';
const INVALID_SIGNUP_TOKEN = 'INVALID_SIGNUP_TOKEN';
const ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN';

module.exports = {
  UNKNOWN_ERROR,
  EMAIL_ALREADY_SIGNED_UP,
  INVALID_SIGNUP_TOKEN,
  ACCESS_FORBIDDEN
};
